# Generated by Django 5.2.1 on 2025-05-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_address_line2_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
